packages:
  - nuxt-app
  - vite-app

catalogs:
  dev:
    '@antfu/eslint-config': ^5.3.0
    '@types/node': ^24.3.0
    '@vitejs/plugin-vue': ^6.0.1
    '@vue/tsconfig': ^0.8.1
    eslint: ^9.35.0
    serve: ^14.2.4
    typescript: ^5.9.2
    unplugin-vue-router: https://pkg.pr.new/unplugin-vue-router@e5a73fc
    vite: ^7.1.4
    vue-tsc: ^3.0.6
  frontend:
    nuxt: ^4.1.2
    vue: ^3.5.19
    vue-router: https://pkg.pr.new/vue-router@7d6164a

onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
